# http://country.io/continent.json
country_to_continent_mapping = {
    "BF":"AF",
    "BI":"AF",
    "BJ":"AF",
    "BW":"AF",
    "RW":"AF",
    "RE":"AF",
    "GW":"AF",
    "GQ":"AF",
    "GA":"AF",
    "GN":"AF",
    "GM":"AF",
    "GH":"AF",
    "TN":"AF",
    "ZM":"AF",
    "EH":"AF",
    "EG":"AF",
    "ZA":"AF",
    "ET":"AF",
    "SO":"AF",
    "ZW":"AF",
    "ER":"AF",
    "MG":"AF",
    "MA":"AF",
    "ML":"AF",
    "MU":"AF",
    "MW":"AF",
    "MR":"AF",
    "UG":"AF",
    "TZ":"AF",
    "SH":"AF",
    "NA":"AF",
    "NE":"AF",
    "NG":"AF",
    "CI":"AF",
    "CM":"AF",
    "CG":"AF",
    "CF":"AF",
    "CD":"AF",
    "CV":"AF",
    "SZ":"AF",
    "KE":"AF",
    "SS":"AF",
    "KM":"AF",
    "ST":"AF",
    "SN":"AF",
    "SL":"AF",
    "SC":"AF",
    "SD":"AF",
    "DJ":"AF",
    "DZ":"AF",
    "YT":"AF",
    "LR":"AF",
    "LS":"AF",
    "TG":"AF",
    "TD":"AF",
    "LY":"AF",
    "AO":"AF",
    "MZ":"AF",
    "BV":"AN",
    "GS":"AN",
    "HM":"AN",
    "TF":"AN",
    "AQ":"AN",
    "BD":"AS",
    "BN":"AS",
    "BH":"AS",
    "BT":"AS",
    "TM":"AS",
    "TJ":"AS",
    "JP":"AS",
    "GE":"AS",
    "OM":"AS",
    "JO":"AS",
    "HK":"AS",
    "PS":"AS",
    "IQ":"AS",
    "PK":"AS",
    "PH":"AS",
    "VN":"AS",
    "SA":"AS",
    "UZ":"AS",
    "MM":"AS",
    "MO":"AS",
    "MN":"AS",
    "MV":"AS",
    "MY":"AS",
    "IL":"AS",
    "IO":"AS",
    "NP":"AS",
    "CN":"AS",
    "CC":"AS",
    "CX":"AS",
    "SY":"AS",
    "KG":"AS",
    "KH":"AS",
    "KR":"AS",
    "KP":"AS",
    "KW":"AS",
    "KZ":"AS",
    "SG":"AS",
    "YE":"AS",
    "LB":"AS",
    "LA":"AS",
    "TW":"AS",
    "TR":"AS",
    "LK":"AS",
    "TH":"AS",
    "AE":"AS",
    "AF":"AS",
    "IR":"AS",
    "AM":"AS",
    "IN":"AS",
    "AZ":"AS",
    "ID":"AS",
    "QA":"AS",
    "BE":"EU",
    "BG":"EU",
    "BA":"EU",
    "JE":"EU",
    "BY":"EU",
    "RU":"EU",
    "RS":"EU",
    "RO":"EU",
    "GR":"EU",
    "GG":"EU",
    "GB":"EU",
    "GI":"EU",
    "HR":"EU",
    "HU":"EU",
    "PT":"EU",
    "SJ":"EU",
    "PL":"EU",
    "EE":"EU",
    "IT":"EU",
    "ES":"EU",
    "ME":"EU",
    "MD":"EU",
    "MC":"EU",
    "MK":"EU",
    "MT":"EU",
    "IM":"EU",
    "FR":"EU",
    "FI":"EU",
    "FO":"EU",
    "NL":"EU",
    "NO":"EU",
    "XK":"EU",
    "CH":"EU",
    "CZ":"EU",
    "CY":"EU",
    "SK":"EU",
    "SI":"EU",
    "SM":"EU",
    "SE":"EU",
    "DK":"EU",
    "DE":"EU",
    "LI":"EU",
    "LV":"EU",
    "LT":"EU",
    "LU":"EU",
    "VA":"EU",
    "AD":"EU",
    "IS":"EU",
    "AL":"EU",
    "AT":"EU",
    "AX":"EU",
    "IE":"EU",
    "UA":"EU",
    "BB":"NA",
    "BL":"NA",
    "BM":"NA",
    "JM":"NA",
    "BQ":"NA",
    "BS":"NA",
    "BZ":"NA",
    "GT":"NA",
    "GP":"NA",
    "GD":"NA",
    "SV":"NA",
    "GL":"NA",
    "HT":"NA",
    "HN":"NA",
    "PR":"NA",
    "PA":"NA",
    "PM":"NA",
    "MF":"NA",
    "MQ":"NA",
    "MS":"NA",
    "MX":"NA",
    "NI":"NA",
    "CA":"NA",
    "CR":"NA",
    "CW":"NA",
    "CU":"NA",
    "SX":"NA",
    "KN":"NA",
    "KY":"NA",
    "DO":"NA",
    "DM":"NA",
    "VG":"NA",
    "US":"NA",
    "LC":"NA",
    "TT":"NA",
    "TC":"NA",
    "VC":"NA",
    "AG":"NA",
    "AI":"NA",
    "VI":"NA",
    "AW":"NA",
    "WF":"OC",
    "WS":"OC",
    "TL":"OC",
    "TK":"OC",
    "GU":"OC",
    "PW":"OC",
    "PF":"OC",
    "PG":"OC",
    "PN":"OC",
    "SB":"OC",
    "MH":"OC",
    "MP":"OC",
    "FJ":"OC",
    "FM":"OC",
    "VU":"OC",
    "NC":"OC",
    "NF":"OC",
    "NZ":"OC",
    "NR":"OC",
    "NU":"OC",
    "CK":"OC",
    "KI":"OC",
    "UM":"OC",
    "TV":"OC",
    "TO":"OC",
    "AS":"OC",
    "AU":"OC",
    "BO":"SA",
    "BR":"SA",
    "GY":"SA",
    "GF":"SA",
    "VE":"SA",
    "PY":"SA",
    "PE":"SA",
    "EC":"SA",
    "FK":"SA",
    "CO":"SA",
    "CL":"SA",
    "SR":"SA",
    "UY":"SA",
    "AR":"SA"
    }

def guess_server_country(gamestats):
    """ Return region based on server country or name. """
    region = None
    
    if "serverinfo" in gamestats:
        country = gamestats["serverinfo"].get("serverCountry", None)
        server_name = gamestats["serverinfo"].get("serverName", "")
    
    # hard manual overrides
    if "virginia"   in server_name.lower(): region = 'na'
    if "chicago"    in server_name.lower(): region = 'na'
    if "miami"      in server_name.lower(): region = 'na'
    if "amster"     in server_name.lower(): region = 'eu'
    if "london"     in server_name.lower(): region = 'eu'
    if "chile"      in server_name.lower(): region = 'sa'
    if "brazil"     in server_name.lower(): region = 'sa'
    
    # use continent dictionary
    if region:
        print("Assigned region using hard manual overrides")
    else:
        if country:
            region = country_to_continent_mapping.get(country,None)
        if region in ["NA","EU","SA"]:
            print("Assigned region using continent dictionary")
        elif region:
            print("Don't like this region " + region)
            region = None
        
    # desperate manual overrides
    if not region:
        if " na"        in server_name.lower(): region = 'na'
        if "-na "       in server_name.lower(): region = 'na'
        if " donkz "    in server_name.lower(): region = 'na'
        if " eu "       in server_name.lower(): region = 'eu'
        if "-eu "       in server_name.lower(): region = 'eu'
        if "adlad"      in server_name.lower(): region = 'eu'
        if " sa "       in server_name.lower(): region = 'sa'
        if "hyperion"   in server_name.lower(): region = 'eu'
        if region:
                print("Assigned region using desperate manual overrides")
        
    if not region: 
        region = 'unk'
        print("Could not assign region. Returning unk value.")
    return region.lower()
    